<a href="https://colab.research.google.com/github/Rachanashenoy20/Machine-Learning/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Creating an array
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
#Creating a 0-D array with value 48
import numpy as np

arr = np.array(48)

print(arr)

48


In [ ]:
#Checking Dimensions that arrays have
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [ ]:
#Printing 2nd and 3rd element from array and adding them
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[1] + arr[2])

5


In [ ]:
#Slice index from 2 to 5
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[2:5])

[3 4 5]


In [ ]:
#Finding data type of the Numpy array
import numpy as np

arr = np.array([1, 2, 3])

print(arr.dtype)

int64


In [ ]:
#copy,change the array and displaying both
import numpy as np

r = np.array([1, 2, 3, 4, 5])
x = r.copy()
r[0] = 42

print(r)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [ ]:
#Converting array into 1-D
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


In [ ]:
#Concatenate two arrays
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [ ]:
#Stack vertically
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
#Splitting the array in 3parts
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
#Finding index whose value is 8
import numpy as np

arr = np.array([1, 2, 8, 8, 5, 8, 4])

x = np.where(arr == 8)

print(x)

(array([2, 3, 5]),)


In [ ]:
#Sorting the array
import numpy as np

arr = np.array([39, 24, 10, 1])

print(np.sort(arr))

[ 1 10 24 39]
